flashcards/urls.py
from django.urls import path

from . import views

app_name = 'flashcards'
urlpatterns = [
    # Set
    path('', views.IndexView.as_view(), name='index'),
    path('create_set/', views.SetCreate.as_view(), name='create_set'),
    path('set/<int:pk>/', views.set_view, name='set_view'),

    # Card
    path('set/<int:set_id>/cards/', views.cards_start, name='cards_start'),
    path('set/<int:set_id>/update_card/<int:pk>', views.CardUpdate.as_view(), name='update_card'),
    path('set/<int:set_id>/create_card', views.CardCreate.as_view(), name='create_card'),
    path('set/<int:set_id>/cards/get_cards/', views.get_cards, name='get_cards'),
    path('set/<int:set_id>/cards/answer/', views.answer, name='answer'),
    path('set/<int:set_id>/cards/next_card/', views.next_card, name='next_card'),

    # Word Search
    path('set/<int:set_id>/search_word/', views.search_word, name='search_word'),
    path('set/<int:set_id>/word_search/', views.word_search, name='word_search'),
    path('set/<int:set_id>/word_search/search_word/', views.search_word, name='search_word'),
]

momoapp/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views

urlpatterns = [
    path('flashcards/', include('flashcards.urls')),
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
]

flashcards/models.py
from django.db import models
from django.urls import reverse

class Language(models.Model):

    name = models.CharField(max_length=200, default="Spanish")

    def __str__(self):
        return self.name

class Set(models.Model):

    language = models.ForeignKey(Language, on_delete=models.CASCADE, default="")
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('flashcards:set_view', args=[self.id])

class Card(models.Model):
    language_word = models.CharField(max_length=200)
    native_word = models.CharField(max_length=200)
    set = models.ForeignKey(Set, on_delete=models.CASCADE, default="", related_name='cards')

    def __str__(self):
        return f"{self.set.name}: {self.language_word}"

    def get_absolute_url(self):
        return reverse('flashcards:set_view', args=[self.set.id])

flashcards/views.py
from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Card, Set
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.conf import settings
from django.views.generic.edit import CreateView, UpdateView
from django.core import serializers

import json
import pprint
import requests
import random

class IndexView(generic.ListView):
    template_name = 'flashcards/index.html'
    model = Set
    context_object_name = 'sets'

class CardCreate(CreateView):
    model = Card
    fields = ['set', 'language_word', 'native_word']

class CardUpdate(UpdateView):
    model = Card
    fields = ['language_word', 'native_word']
    template_name_suffix = '_update_form'

class SetCreate(CreateView):
    model = Set
    fields = ['name', 'language']

# --------- View rendering functions --------- #
def set_view(request, pk):
    """
        Renders Set View
    """
    return render(request, 'flashcards/set.html', {
        'cards': Card.objects.filter(set=pk),
        'set_id': pk,
    })

def cards_start(request, set_id):
    """
        Renders flashcards view 
    """
    return render(request, 'flashcards/cards.html', {
        'set_id': set_id,
    })

def word_search(request, set_id):
    """
        Calls word search view
    """
    return render(request, 'flashcards/word_search.html', {
        'set_id': set_id,
    })

#--------- Flashcard js functions ---------#

def answer(request, set_id):
    """
        Checks submitted card answer to see if correct
    """
    if request.method == 'POST':
        card = get_object_or_404(Card, pk=int(request.POST['card_id']))
        response_data = {}
        answer = request.POST['answer_text']
        if card.native_word.lower() == answer.lower():
            response_data['correct_answer'] = True
            return HttpResponse(
                json.dumps(response_data),
                content_type="application/json"
            )
        else:
            return HttpResponse(
                json.dumps({"correct_answer": False}),
                content_type="application/json"
            )

def next_card(request, set_id):
    """
        Collects next card from passed id
    """
    try:
        if request.method == 'POST':
            next_card = Card.objects.get(pk=int(request.POST['card_id']))
            return HttpResponse(
                json.dumps({"pk": next_card.pk, "front_word" : next_card.language_word, "back_word": next_card.native_word }),
                content_type="application/json"
            )
    except:
        return HttpResponse(
                json.dumps({"next_card": False}),
                content_type="application/json"
            )

def get_cards(request, set_id):
    """
        Returns a randomised array of ids for cards of set and the values of first card
    """
    cards = Card.objects.filter(set=set_id)
    ids = [ card.id for card in cards ]

    # Randomise cards
    random.shuffle(ids)
    card = Card.objects.get(pk=ids[0])
    return HttpResponse(
            json.dumps({"card_ids": ids, 'first_card': {'pk': card.pk, 'front_word': card.language_word, 'back_word' : card.native_word}}),
            content_type="application/json"
        )
        
def search_word(request, set_id):
    """
        Gets word from form and passes to the Merriam Webster API. returning result of search
    """
    if request.method == 'POST':
        result = {}
        word = request.POST['word']

        if word:
            endpoint = 'https://dictionaryapi.com/api/v3/references/spanish/json/{word_id}?key={key}'
            url = endpoint.format(key=settings.MERRIAM_WEBSTER_APP_ID, word_id=word)
            response = requests.get(url)
            result = response.json()

            if response.status_code == 200:
                result = response.json()
                result.append({'message': False})
            else:
                if response.status_code == 404:
                    result.append({'message': 'No entry found for "%s"' % word})
                else:
                    result.append({'message': 'The Merriam Webster API is not available at the moment. Please try again later.'})
            return HttpResponse(
                json.dumps(result),
                content_type="application/json"
            )

momoapp/views.py
from django.views.generic.base import TemplateView

class IndexView(TemplateView):
    template_name = 'home.html'

flashcards/templates/flashcards/card.html
{% include 'base.html' %}
{% load static %}


{% block head_css %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/style.css' %}">
<!-- <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/index.css' %}"> -->
{% endblock %}

{% block body_main %}
<a id="vflashcards">
    <div class="container">
        <section class="flip-card flashcards">
        <div class="flashcard-inner" id="flashcard" v-bind:class="{'rotate-card': flipped}">
            <div class="flashcard-front" id="flashcard-front">
                <form id="card-form" action="{% url 'flashcards:answer' set_id %}" method="post" autocomplete="off">
                    <h1 id="front_word"></h1>
                    {% csrf_token %}
                    <input type="text" id="answer_text" name="answer_text">
                    <input class="btn-primary" type="submit" value="Submit" id="submit">
                </form>
                {% if wrong_answer %}
                    <div class="alert alert-danger" role="alert">
                        <p><strong>{{ wrong_answer }}</strong></p>
                    </div>
                {% endif %}
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            </div>
            <div class="flashcard-back" id="flashcard-back">
                <!-- <h2> {{ card.native_word}}</h2> -->
                <form id="next-card-form" action="{% url 'flashcards:next_card' set_id %}" method="post">
                    <h1 id="back_word"></h1>
                    <input class="btn-primary" type="submit" value="Next" id="submit">
                </form>
            </div>
            </div>
        </section>
        <input type="number" id ="card_id" hidden></input>
    </div>
</a>

{% endblock %}

{% block footer_javascript_site %}
<script src="{% static 'flashcards/js/flashcards.js' %}" type="text/javascript"></script>
{% endblock %}

flashcards/templates/flashcards/card_form.html
{% include 'base.html' %}
{% load static %}

{% block head_css %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/index.css' %}">
{% endblock %}

{% block body_main %}
<div class="container">
    <h2>Create new card</h2>
    <form method="post">{% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <input type="submit" value="Save">
    </form>
</div>
{% endblock %}

{% block footer_javascript_site %}
<script src="{% static 'flashcards/js/card_form.js' %}" type="text/javascript"></script>
{% endblock %}

flashcards/templates/flashcards/card_update_form.html
{% include 'base.html' %}
{% load static %}


{% block head_css %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
{% endblock %}

{% block body_main %}
<a id="vflashcards">
    <div class="container">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
</a>

{% endblock %}

flashcards/templates/flashcards/cards.html
{% include 'base.html' %}
{% load static %}


{% block head_css %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/style.css' %}">
<!-- <link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/index.css' %}"> -->
{% endblock %}

{% block body_main %}
<a id="vflashcards">
    <div class="container">
        <section class="flip-card flashcards">
        <div class="flashcard-inner" id="flashcard" v-bind:class="{'rotate-card': flipped}">
            <div class="flashcard-front" id="flashcard-front">
                <form id="card-form" action="{% url 'flashcards:answer' set_id %}" method="post" autocomplete="off">
                    <h1> [[front_word]] </h1>
                    {% csrf_token %}
                    <input type="text" v-model="answer_text">
                    <input class="btn-primary" type="submit" value="Submit" id="submit">
                </form>
                {% if wrong_answer %}
                    <div class="alert alert-danger" role="alert">
                        <p><strong>{{ wrong_answer }}</strong></p>
                    </div>
                {% endif %}
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            </div>
            <div class="flashcard-back" id="flashcard-back">
                <form id="next-card-form" action="{% url 'flashcards:next_card' set_id %}" method="post">
                    <h1> [[back_word]] </h1>
                    <input class="btn-primary" type="submit" value="Next" id="submit">
                </form>
            </div>
            </div>
        </section>
        <input type="number" v-model="card_id" hidden></input>
    </div>
</a>

{% endblock %}

{% block footer_javascript_site %}
<script src="{% static 'flashcards/js/flashcards.js' %}" type="text/javascript"></script>
{% endblock %}

flashcards/templates/flashcards/index.html
{% include 'base.html' %}
{% load static %}

{% block head_css %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/index.css' %}">
{% endblock %}

{% block body_main %}

{% if sets %}
<div class="container">
  <h2>Sets</h2>
  <ul class="list-group">
    {% for set in sets %}
    <li class="list-group-item"><a href="{% url 'flashcards:set_view' set.id %}">{{ set.name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
    <p>No sets are available.</p>
{% endif %}

  <div class="btn-bottom">
    <div class="row">
      <div class="col-12">
      <form action="{% url 'flashcards:create_set' %}">
          <input type="submit" value="Create" class="btn btn-dark"/>
      </form>
    </div>
    </div>
  </div>
</div>


{% endblock %}

flashcards/templates/flashcards/set.html
{% include 'base.html' %}
{% load static %}

{% block head_css %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
{% endblock %}

{% block body_main %}
<div class="container">
  <h2>Cards</h2>
  <div>
    <ul class="list-group">
    {% if cards %}
      {% for card in cards %}
      <li class="list-group-item"><a href="{% url 'flashcards:update_card' set_id=set_id pk=card.id %}">{{ card.language_word }}</a></li>
      {% endfor %}
    {% else %}
    <p>No cards are available.</p>
    {% endif %}
  </ul>
</div>

<div class="btn-bottom">
  <div class="row">
    <div class="col-4">
      <form action="{% url 'flashcards:cards_start' set_id %}">
          <input type="submit" value="Start" class="btn btn-dark"/>
        </form>
      </div>
    <div class="col-4">
    <form action="{% url 'flashcards:create_card' set_id %}">
        <input type="submit" value="Create" class="btn btn-dark"/>
      </form>
    </div>
  <div class="col-4">
    <form action="{% url 'flashcards:word_search' set_id %}">
        <input type="submit" value="Word Search" class="btn btn-dark"/>
    </form>
  </div>
</div>
</div>
{% endblock body_main %}

flashcards/templates/flashcards/set_form.html
{% include 'base.html' %}
{% load static %}

{% block head_css %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/index.css' %}">
{% endblock %}

{% block body_main %}
<div class="container">
    <h2>Create new set</h2>
    <form method="post">{% csrf_token %}
        <div class="row">
            <div class="col form-group">
                {{ form.language.errors }}
                <label class="form-check-label" for="{{ form.language.id_for_label }}">Language:</label>
                {{ form.language }}
            </div>
        </div>
        <div class="row">
            <div class="col form-group">
                {{ form.name.errors }}
                <label class="form-check-label" for="{{ form.name.id_for_label }}">Set name:</label>
                {{ form.name }}
            </div>
        </div>
        <div class="row">
            <input class="offset-4 col-4" type="submit" value="Save">
        </div>
    </form>
</div>
{% endblock %}

flashcards/templates/flashcards/word_search.html
{% include 'base.html' %}
{% load static %}

{% block head_css %}
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'flashcards/css/index.css' %}">
{% endblock %}


{% block body_main %}
<a id="vwordsearch">
    <div class="container">
        <div>
            <form id="search-form" action="{% url 'flashcards:search_word' set_id %}" method="post" autocomplete="off">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" id="language_word" v-model='language_word'>
                    <label class="form-check-label" for="language_word">Language Word</label>
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" id="native_word" v-model='native_word'>
                    <label class="form-check-label" for="native_word">Native Word</label>
                </div>
                <div class="form-group">
                    <input class="btn-primary" type="submit" value="Search">
                </div>
            </form>
        </div>

        <div id="results-table" class="table-responsive" v-if="words.length">
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th scope="col" v-for="(column, index) in columns" :key="index"> [[column]]</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, index) in words" :key="index">
                        <td v-for="(column, indexColumn) in columns" :key="indexColumn">
                            <li v-for="word in item[column]">
                                [[ word ]]
                            </li>
                        </td>
                    </tr>
                </tbody>
              </table>
        </div>
        <div class="alert alert-warning" role="alert" v-if="!words.length">
            No results found
          </div>
    </div>
</a>

{% endblock %}

{% block footer_javascript_site %}
<script src="{% static 'flashcards/js/word_search.js' %}" type="text/javascript"></script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    {# Make modifiable head elements #}
    <head>
        <title>{% block title %} Home {% endblock title %} | Momo</title>
        {% block head_favicon %}
            <link rel="shortcut icon" type="image/png"
                  href="{% static 'images/momo-favicon.png' %}">
        {% endblock head_favicon %}
        {% block head_meta %}
            {% block head_meta_charset %}
                <meta http-equiv="Content-Type"
                      content="text/html; charset=utf-8" />
            {% endblock head_meta_charset %}
            {% block head_meta_contentlanguage %}
                <meta http-equiv="Content-Language" value="en-US" />
            {% endblock head_meta_contentlanguage %}
            {% block head_meta_viewport %}
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0">
            {% endblock head_meta_viewport %}
        {% endblock head_meta %}
        {% block head_css %}
            {% block head_css_site %}
                    <link href="{% static 'bootstrap-4.5.3-dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
                    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">
            {% endblock head_css_site %}
            {% block head_css_section %}{% endblock head_css_section %}
            {% block head_css_page %}{% endblock head_css_page %}
        {% endblock head_css %}
    </head>

    <!-- <body>
        {# Navigation Menu #}
        <header>
            <div class="navbar navbar-default navbar-static-top 
            {% block nav-style %}{% endblock %}">
                <div class="container p-none">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle"
                                data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">Momo</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                <li><a href="">Logout</a></li>
                                <li><a href=""
                                       class="p-r-none">Accounts</a></li>
                            {% else %}
                                <li><a href="">Login</a></li>
                                <li><a href="" class="p-r-none">Sign Up</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        {# The Document Body #}
        <div id="site-wrapper">
            {% block content %}
                if you see this, something is wrong!
            {% endblock content %}
        </div>
        {# The Footer #}
        <div class="footer">
            <div class="container">
                <p>Copyright CRM Easy</p>
            </div>
        </div>
    </body> -->
    <body> 
      
        <!-- Header Section -->
        <header> 
            <div class="head1">Momo </div> 
        </header> 
          
        {% block nav_bar %}
        <!-- Menu Navigation Bar -->
        <div class="menu"> 
            <a href="/">HOME</a> 
            <a href="/flashcards">FLASHCARDS</a> 
            <a href="#info">INFORMATION</a> 
            <div class="menu-log"> 
                <a href="#login">LOGIN</a> 
            </div> 
        </div> 
        {% endblock nav_bar %}
          
        {% block body_main %}
        {% endblock body_main %}

        <!-- Footer Section -->
        <!-- {% block footer_main %}
        <div class="footer">
            <div class="container">
                <p>Footer Section</p>
            </div>
        </div>
        {% endblock footer_main %} -->

    </body>
    

    {# Set of blocks that can be used to display JavaScript files #}
    {% block footer_javascript %}
        {% block footer_javascript_site %}
            <script src="{% static '/js/jquery-3.5.1.min.js' %}" type="text/javascript"></script>
            <script src="{% static 'bootstrap-4.5.3-dist/js/bootstrap.js' %}" type="text/javascript"></script>
            <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        {% endblock footer_javascript_site %}
        {% block footer_javascript_section %}{% endblock footer_javascript_section %}
        {% block footer_javascript_page %}{% endblock footer_javascript_page %}
    {% endblock footer_javascript %}
</html>

templates/home.html
{% include 'base.html' %}
{% load static %}

<div class="container container-main">
    <p> Welcome to Momo!</p>
</div>